### ISSUE TITLE
Search operator in queryMessage()

### ISSUE THREAD

**Issue by mfgabriel92** [fedecia/gmail-api-sync#2]
I was having issues to make use of `newer_than` search operator and I checked the [file](https://github.com/fedecia/gmail-api-sync/blob/master/index.js#L356) and noticed it's accessing `query` from `options`. Doesn't it mean only `query` will work? What about `newer_than` and others?

**Comment by fedecia** [comment]
Maybe the example wasn't clear enough, my bad. 
```
var options = {query: 'from:facebook.com newer_than:2d'};
```
You can have as many search operators as you want separated by a space.

**Comment by mfgabriel92** [comment]
@fedecia Oh! I see! Thank you!

**Comment by fedecia** [comment]
No worries.
